[package]
edition = "2021"
name = "plotsaur"
publish = false
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
plotters-iced = "0.1.4"
iced_wgpu = "0.4.0"
iced_winit = "0.3.0"
plotters = "0.3"
futures = "0.3.19"
